apiVersion: v1
kind: Secret
metadata:
  name: stockit-be-secret
  namespace: default
type: Opaque
data:
  db-pass: "cXdlcjEyMzQhIQ=="
  db-user: "dXNlcg=="
  jwt-secret: "c3RvY2tpdC1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbi1tdXN0LWJlLXZlcnktbG9uZy0yNTZiaXQ="
  openai-api-key: "c2stcHJvai1wOHUxQkJoSGM3Yi1ucjFubHB2RWFiRGpIc201MUJVWkl5LWJ2SkZ5N1F5LUpqOG53R0V0ZDNVUUlCVkUxMW02VlkwQllYZERKdFQzQmxia0ZKemtCb1pidlVWcVpDU1FITkMwSjFIRzBEZGI1eEp1dEtfRDNwRWlCTXdLcC0xOF81RWdCTWU5U29YRTlFQ3ZIWjNNNWNZNWNKVUE="
  public-data-api-key: "NGY4NGQ2YmZjNWI0MzEyYTZmOTc5MmUwNGUwNDkzNDAwMzU1MTkyYThmM2RiMmU5YjFjNGQxNjQwYmUzOWQxMA=="
  admin-bootstrap-password: "U3RvY2tpdCEyMDI2"
